version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"

  - package-ecosystem: github-actions
    directores:
    - "/"
    - ".github/actions/*"
    schedule:
      interval: daily
