name: Docker Build
description: Builds linkerd's docker images

inputs:
  docker-registry:
    description: The docker registry used to tag the images
    required: false
    default: cr.l5d.io/linkerd
  docker-target:
    description: The OS-arch the docker build will be targeted to
    required: false
    default: linux-amd64
  docker-push:
    description: Whether to push the built images to the registry
    required: false
    default: ''
  docker-ghcr-token:
    description: GH token with image publishing access
    required: false
  tag:
    description: Tag to use for the built image
    required: true

runs:
  using: composite
  steps:
    - name: Configure cache
      shell: bash
      run: echo "DOCKER_BUILDKIT_CACHE=${{ runner.temp }}/.buildx-cache" >> $GITHUB_ENV
    - uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0
      with:
        path: ${{ env.DOCKER_BUILDKIT_CACHE }}
        key: ${{ runner.os }}-buildx-linkerd-extension-init-${{ inputs.tag }}
        restore-keys: ${{ runner.os }}-buildx-linkerd-extension-init-

    - uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130
    - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
    - uses: linkerd/dev/actions/setup-tools@v48
    - env:
        DOCKER_TARGET: ${{ inputs.docker-target }}
        DOCKER_PUSH: ${{ inputs.docker-push }}
      shell: bash
      run: |
        if [[ -n "${{ inputs.docker-push }}" ]];then
          echo "${{ inputs.docker-ghcr-token }}" | docker login ghcr.io -u $ --password-stdin
        fi
        just build-image ${{ inputs.docker-registry }} ${{ inputs.tag }}

    # Delete older docker images to prevent cache bloat.
    - uses: linkerd/dev/actions/setup-tools@v48
    - shell: bash
      run: just-dev prune-action-cache ${{ env.DOCKER_BUILDKIT_CACHE }}

outputs:
  image:
    description: The image that was built
    value: ${{ inputs.docker-registry }}/extension-init:${{ inputs.tag }}
