name: Integration tests

on:
  pull_request: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
    - uses: linkerd/dev/actions/setup-tools@v48
    - run: just build
    - run: just integration-test
