name: Integration tests

on:
  pull_request: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - uses: linkerd/dev/actions/setup-tools@v50
    - run: just build
    - run: just integration-test
