name: markdown

permissions:
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/markdown.yml
      - '**/*.md'

jobs:
  markdownlint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b
        with:
          globs: |
            **/*.md
            !**/node_modules/**
            !target/**
